const CURRENT_TERMS_VERSION = "2026-06-15";
const CURRENT_PRIVACY_VERSION = "2026-06-15";
const CURRENT_AGE_CONFIRMATION_VERSION = "2026-06-15";

module.exports = {
  CURRENT_TERMS_VERSION,
  CURRENT_PRIVACY_VERSION,
  CURRENT_AGE_CONFIRMATION_VERSION,
};
