ALTER TABLE users
  ADD COLUMN IF NOT EXISTS district VARCHAR(255);

ALTER TABLE teams
  ADD COLUMN IF NOT EXISTS district VARCHAR(255);

ALTER TABLE team_vacant_roles
  ADD COLUMN IF NOT EXISTS district VARCHAR(255);
